#include "record.h"


void MysteriousStrengthen(FILE *outFile,int type,char *id,char *name,int allnumber[MAXNUM][2],int level,int quality,int picture,char itemtype[MAXNUMWEA][CHAR],char numbertype[MAXNUMWEA][CHAR],char handtype[MAXNUMWEA][CHAR],char taketype[MAXNUMWEA][CHAR],char picturetype[MAXNUMWEA][CHAR],char mowen[MAXNUMWEA][CHAR],char catetype[MAXNUMWEA][CHAR],char mpicturetype[MAXNUMWEA][CHAR],char mmpicturetype[MAXNUMWEA][CHAR],int power[MAXNUMWEA],int numberkind[MAXNUMWEA]){
	int temp1,temp2;
	char filename3[CHAR];	
	FILE *singleFile;
	char str1[20] = "普通的";	
	char str2[20] = "优秀的";
	char str3[20] = "精良的";
	char str4[20] = "史诗的";
	char str5[20] = "传说的";
	char str[20] = ".yml";
	char path[200] = "MysteriousStrengthen\\方案\\";
	char temppath[200];

	int money = level*level; 
	int number = 0;		
	number = allnumber[level][numberkind[type]];
	number = number*power[type]/100;
	int numberlite = number*0.1;

	//普通 
	strcpy(filename3,str1);
	strcat(filename3,name);
	
	fprintf(outFile,"'putong%s':\n",id);	
	fprintf(outFile,"  装备名称: '%s'\n",filename3);
	fprintf(outFile,"  强化方案: '%s'\n",filename3);
	

	strcat(filename3,str);
	strcpy(temppath,path);
	strcat(temppath,filename3);
	strcpy(filename3,temppath);	
	singleFile = fopen(filename3,"w");	
	fputs("使用的GUI: '装备强化GUI.yml'\n",singleFile);
	fputs("强化属性书写在的lore下: '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&3&l[ 强化 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",singleFile);
	fputs("强度:\n",singleFile);
	fputs("  获取强度: '&f>> &7强化等级:'\n",singleFile);
	fputs("  满级: 3\n",singleFile);
	fputs("  强度条:\n",singleFile);
	fputs("    开启: true\n",singleFile);
	fputs("    符号: '★'\n",singleFile);
	fputs("    前缀: '&e['\n",singleFile);
	fputs("    后缀: '&e]'\n",singleFile);
	fputs("    强化颜色: 'ab5'\n",singleFile);
	fputs("    背景颜色: '8'\n",singleFile);
	fputs("  文字强度:\n",singleFile);
	fputs("    开启: false\n",singleFile);
	fputs("    文字: '&8零,&7壹,&4贰,&c叁,&5肆,&d伍,&6陆,&e柒,&f捌,&b玖,&a拾'\n",singleFile);
	fputs("保护材料:\n",singleFile);
	fputs("  损坏保护石:\n",singleFile);
	fputs("    物品名编号: '4'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '损坏保护几率'\n",singleFile);
	fputs("  降级保护石:\n",singleFile);
	fputs("    物品名编号: '5'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '降级保护几率'\n",singleFile);
	fputs("  提升几率石:\n",singleFile);
	fputs("    物品名编号: '6'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '强化成功几率'\n",singleFile);
	temp1 = 0.5*money;
	temp2 = 0.1*number;
	fputs("等级:\n",singleFile);
	fputs("  '1':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 100\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = money;
	temp2 = 0.2*number;
	fputs("  '2':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 80\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 2*money;
	temp2 = 0.3*number;
	fputs("  '3':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 70\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	fclose(singleFile);
	
	//优秀 
	strcpy(filename3,str2);
	strcat(filename3,name);
	
	fprintf(outFile,"'youxiu%s':\n",id);	
	fprintf(outFile,"  装备名称: '%s'\n",filename3);
	fprintf(outFile,"  强化方案: '%s'\n",filename3);
	

	strcat(filename3,str);
	strcpy(temppath,path);
	strcat(temppath,filename3);
	strcpy(filename3,temppath);		
	singleFile = fopen(filename3,"w");	
	fputs("使用的GUI: '装备强化GUI.yml'\n",singleFile);
	fputs("强化属性书写在的lore下: '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&6&l[ 强化信息 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",singleFile);
	fputs("强度:\n",singleFile);
	fputs("  获取强度: '&f>> &7强化等级:'\n",singleFile);
	fputs("  满级: 5\n",singleFile);
	fputs("  强度条:\n",singleFile);
	fputs("    开启: true\n",singleFile);
	fputs("    符号: '★'\n",singleFile);
	fputs("    前缀: '&e['\n",singleFile);
	fputs("    后缀: '&e]'\n",singleFile);
	fputs("    强化颜色: 'ab53d'\n",singleFile);
	fputs("    背景颜色: '8'\n",singleFile);
	fputs("  文字强度:\n",singleFile);
	fputs("    开启: false\n",singleFile);
	fputs("    文字: '&8零,&7壹,&4贰,&c叁,&5肆,&d伍,&6陆,&e柒,&f捌,&b玖,&a拾'\n",singleFile);
	fputs("保护材料:\n",singleFile);
	fputs("  损坏保护石:\n",singleFile);
	fputs("    物品名编号: '4'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '损坏保护几率'\n",singleFile);
	fputs("  降级保护石:\n",singleFile);
	fputs("    物品名编号: '5'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '降级保护几率'\n",singleFile);
	fputs("  提升几率石:\n",singleFile);
	fputs("    物品名编号: '6'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '强化成功几率'\n",singleFile);
	temp1 = 0.5*money*1.2;
	temp2 = 0.1*number*1.2;
	fputs("等级:\n",singleFile);
	fputs("  '1':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 100\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = money*1.2;
	temp2 = 0.2*number*1.2;
	fputs("  '2':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 80\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 2*money*1.2;
	temp2 = 0.3*number*1.2;
	fputs("  '3':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 70\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 3*money*1.2;
	temp2 = 0.4*number*1.2;
	fputs("  '4':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 60\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 4*money*1.2;
	temp2 = 0.5*number*1.2;
	fputs("  '5':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 50\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	fclose(singleFile);


	//精良 
	strcpy(filename3,str3);
	strcat(filename3,name);
	
	fprintf(outFile,"'jingliang%s':\n",id);	
	fprintf(outFile,"  装备名称: '%s'\n",filename3);
	fprintf(outFile,"  强化方案: '%s'\n",filename3);
	

	strcat(filename3,str);
	strcpy(temppath,path);
	strcat(temppath,filename3);
	strcpy(filename3,temppath);		
	singleFile = fopen(filename3,"w");	
	fputs("使用的GUI: '装备强化GUI.yml'\n",singleFile);
	fputs("强化属性书写在的lore下: '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&6&l[ 强化信息 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",singleFile);
	fputs("强度:\n",singleFile);
	fputs("  获取强度: '&f>> &7强化等级:'\n",singleFile);
	fputs("  满级: 7\n",singleFile);
	fputs("  强度条:\n",singleFile);
	fputs("    开启: true\n",singleFile);
	fputs("    符号: '★'\n",singleFile);
	fputs("    前缀: '&e['\n",singleFile);
	fputs("    后缀: '&e]'\n",singleFile);
	fputs("    强化颜色: 'ab53d2c'\n",singleFile);
	fputs("    背景颜色: '8'\n",singleFile);
	fputs("  文字强度:\n",singleFile);
	fputs("    开启: false\n",singleFile);
	fputs("    文字: '&8零,&7壹,&4贰,&c叁,&5肆,&d伍,&6陆,&e柒,&f捌,&b玖,&a拾'\n",singleFile);
	fputs("保护材料:\n",singleFile);
	fputs("  损坏保护石:\n",singleFile);
	fputs("    物品名编号: '4'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '损坏保护几率'\n",singleFile);
	fputs("  降级保护石:\n",singleFile);
	fputs("    物品名编号: '5'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '降级保护几率'\n",singleFile);
	fputs("  提升几率石:\n",singleFile);
	fputs("    物品名编号: '6'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '强化成功几率'\n",singleFile);
	temp1 = 0.5*money*1.4;
	temp2 = 0.1*number*1.4;
	fputs("等级:\n",singleFile);
	fputs("  '1':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 100\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = money*1.4;
	temp2 = 0.2*number*1.4;
	fputs("  '2':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 80\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 2*money*1.4;
	temp2 = 0.3*number*1.4;
	fputs("  '3':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 70\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 3*money*1.4;
	temp2 = 0.4*number*1.4;
	fputs("  '4':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 60\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 4*money*1.4;
	temp2 = 0.5*number*1.4;
	fputs("  '5':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 50\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 5*money*1.4;
	temp2 = 0.6*number*1.4;
	fputs("  '6':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 6*money*1.4;
	temp2 = 0.7*number*1.4;
	fputs("  '7':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	fclose(singleFile);
	
	
	
	
	//史诗 
	strcpy(filename3,str4);
	strcat(filename3,name);
	
	fprintf(outFile,"'shishi%s':\n",id);	
	fprintf(outFile,"  装备名称: '%s'\n",filename3);
	fprintf(outFile,"  强化方案: '%s'\n",filename3);
	

	strcat(filename3,str);	
	strcpy(temppath,path);
	strcat(temppath,filename3);
	strcpy(filename3,temppath);	
	singleFile = fopen(filename3,"w");	
	fputs("使用的GUI: '装备强化GUI.yml'\n",singleFile);
	fputs("强化属性书写在的lore下: '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&6&l[ 强化信息 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",singleFile);
	fputs("强度:\n",singleFile);
	fputs("  获取强度: '&f>> &7强化等级:'\n",singleFile);
	fputs("  满级: 9\n",singleFile);
	fputs("  强度条:\n",singleFile);
	fputs("    开启: true\n",singleFile);
	fputs("    符号: '★'\n",singleFile);
	fputs("    前缀: '&e['\n",singleFile);
	fputs("    后缀: '&e]'\n",singleFile);
	fputs("    强化颜色: 'ab53d2ce4'\n",singleFile);
	fputs("    背景颜色: '8'\n",singleFile);
	fputs("  文字强度:\n",singleFile);
	fputs("    开启: false\n",singleFile);
	fputs("    文字: '&8零,&7壹,&4贰,&c叁,&5肆,&d伍,&6陆,&e柒,&f捌,&b玖,&a拾'\n",singleFile);
	fputs("保护材料:\n",singleFile);
	fputs("  损坏保护石:\n",singleFile);
	fputs("    物品名编号: '4'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '损坏保护几率'\n",singleFile);
	fputs("  降级保护石:\n",singleFile);
	fputs("    物品名编号: '5'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '降级保护几率'\n",singleFile);
	fputs("  提升几率石:\n",singleFile);
	fputs("    物品名编号: '6'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '强化成功几率'\n",singleFile);
	temp1 = 0.5*money*1.7;
	temp2 = 0.1*number*1.7;
	fputs("等级:\n",singleFile);
	fputs("  '1':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 100\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = money*1.7;
	temp2 = 0.2*number*1.7;
	fputs("  '2':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 80\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 2*money*1.7;
	temp2 = 0.3*number*1.7;
	fputs("  '3':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 70\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 3*money*1.7;
	temp2 = 0.4*number*1.7;
	fputs("  '4':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 60\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 4*money*1.7;
	temp2 = 0.5*number*1.7;
	fputs("  '5':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 50\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 5*money*1.7;
	temp2 = 0.6*number*1.7;
	fputs("  '6':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 6*money*1.7;
	temp2 = 0.7*number*1.7;
	fputs("  '7':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 7*money*1.7;
	temp2 = 0.8*number*1.7;
	fputs("  '8':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 30\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 8*money*1.7;
	temp2 = 0.9*number*1.7;
	fputs("  '9':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 20\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	fclose(singleFile);
	
	


	//传说 
	strcpy(filename3,str5);
	strcat(filename3,name);
	
	fprintf(outFile,"'chuanshuo%s':\n",id);	
	fprintf(outFile,"  装备名称: '%s'\n",filename3);
	fprintf(outFile,"  强化方案: '%s'\n",filename3);
	

	strcat(filename3,str);	
	strcpy(temppath,path);
	strcat(temppath,filename3);
	strcpy(filename3,temppath);	
	singleFile = fopen(filename3,"w");	
	fputs("使用的GUI: '装备强化GUI.yml'\n",singleFile);
	fputs("强化属性书写在的lore下: '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&6&l[ 强化信息 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",singleFile);
	fputs("强度:\n",singleFile);
	fputs("  获取强度: '&f>> &7强化等级:'\n",singleFile);
	fputs("  满级: 9\n",singleFile);
	fputs("  强度条:\n",singleFile);
	fputs("    开启: true\n",singleFile);
	fputs("    符号: '★'\n",singleFile);
	fputs("    前缀: '&e['\n",singleFile);
	fputs("    后缀: '&e]'\n",singleFile);
	fputs("    强化颜色: 'ab53d2ce4'\n",singleFile);
	fputs("    背景颜色: '8'\n",singleFile);
	fputs("  文字强度:\n",singleFile);
	fputs("    开启: false\n",singleFile);
	fputs("    文字: '&8零,&7壹,&4贰,&c叁,&5肆,&d伍,&6陆,&e柒,&f捌,&b玖,&a拾'\n",singleFile);
	fputs("保护材料:\n",singleFile);
	fputs("  损坏保护石:\n",singleFile);
	fputs("    物品名编号: '4'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '损坏保护几率'\n",singleFile);
	fputs("  降级保护石:\n",singleFile);
	fputs("    物品名编号: '5'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '降级保护几率'\n",singleFile);
	fputs("  提升几率石:\n",singleFile);
	fputs("    物品名编号: '6'\n",singleFile);
	fputs("    几率:\n",singleFile);
	fputs("      获取lore: '强化成功几率'\n",singleFile);
	temp1 = 0.5*money*2;
	temp2 = 0.1*number*2;
	fputs("等级:\n",singleFile);
	fputs("  '1':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 100\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = money*2;
	temp2 = 0.2*number*2;
	fputs("  '2':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 80\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 2*money*2;
	temp2 = 0.3*number*2;
	fputs("  '3':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 70\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 0\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '1': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 3*money*2;
	temp2 = 0.4*number*2;
	fputs("  '4':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 60\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 4*money*2;
	temp2 = 0.5*number*2;
	fputs("  '5':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 50\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 5*money*2;
	temp2 = 0.6*number*2;
	fputs("  '6':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '2': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 6*money*2;
	temp2 = 0.7*number*2;
	fputs("  '7':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 40\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 7*money*2;
	temp2 = 0.8*number*2;
	fputs("  '8':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 30\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 2\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 8*money*2;
	temp2 = 0.9*number*2;
	fputs("  '9':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 20\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '3': 4\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	temp1 = 10*money*2;
	temp2 = number*2;
	fputs("  '10':\n",singleFile);
	fprintf(singleFile,"    需要钱数: %d\n",temp1);
	fputs("    成功几率: 10\n",singleFile);
	fputs("    失败损坏: false\n",singleFile);
	fputs("    失败降级数: 1\n",singleFile);
	fputs("    全服消息: \"[NOMSG]\"\n",singleFile);
	fputs("    成功命令: \"[NOCMD]\"\n",singleFile);
	fputs("    强化材料:\n",singleFile);
	fputs("      '7': 1\n",singleFile);
	fputs("    强化属性:\n",singleFile);
	fprintf(singleFile,"    - '&f>> &7附加%s:%d'\n",numbertype[type],temp2);
	fclose(singleFile);
	
}

