#include "record.h"


void RandomForge(FILE *outFile,int type,char *id,char *name,int allnumber[MAXNUM][2],int level,int quality,int picture,char itemtype[MAXNUMWEA][CHAR],char numbertype[MAXNUMWEA][CHAR],char handtype[MAXNUMWEA][CHAR],char taketype[MAXNUMWEA][CHAR],char picturetype[MAXNUMWEA][CHAR],char mowen[MAXNUMWEA][CHAR],char catetype[MAXNUMWEA][CHAR],char mpicturetype[MAXNUMWEA][CHAR],char mmpicturetype[MAXNUMWEA][CHAR],int power[MAXNUMWEA],int numberkind[MAXNUMWEA]){
	int temp1,temp2,temp3;
	int money = level*level*10; 
	int number = 0;	
	number = allnumber[level][numberkind[type]];
	number = number*power[type]/100;	
	int numberlite = number*0.1;
	
	fprintf(outFile,"  %s:\n",id);
	fprintf(outFile,"    id: %s\n",picturetype[type]);
	fputs("    data: 0\n",outFile);
	fprintf(outFile,"    display: '<鉴定品质>的%s'\n",name);
	fputs("    lores:\n",outFile);
	fprintf(outFile,"    - '&0%d'\n",picture);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&a&l[ 基础 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile);
	fprintf(outFile,"    - '&f>> &7部位:%s'\n",handtype[type]);
	fprintf(outFile,"    - '&f>> &7类型:%s'\n",taketype[type]);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&b&l[ 属性 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile);
	fprintf(outFile,"    - '&f>> &7%s:<特殊值>' \n",numbertype[type]);
	fputs("    - '&f>> &7强度:&e[<strength>&e]'\n",outFile);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&c&l[ 需求 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile); 
	fprintf(outFile,"    - '&f>> &7精通需求:%s精通'\n",itemtype[type]);
	fputs("    - '&f>> &7等级需求:<等级>'\n",outFile);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&e&l[ 交易 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile);
	fputs("    - '&f>> &7回收价格:<价值>'\n",outFile);
	fputs("    - '&c&l不可交易'\n",outFile);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&d&l[ 宝珠 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile);
	fputs("    - '&f◎ &7[<孔2>]'\n",outFile);
	fputs("    - '&f◎ &7[<孔3>]'\n",outFile);
	fputs("    - '&f◎ &7[<孔4>]'\n",outFile);
	fputs("    - '&f◎ &7[<孔5>]'\n",outFile);
	fputs("    - '&f◎ &7[<孔6>]'\n",outFile);
	fputs("    - '&d&l&m--&4&l&m--&c&l&m--&6&l&m--&e&l&m--&3&l[ 强化 ]&a&l&m--&2&l&m--&b&l&m--&3&l&m--&9&l&m--'\n",outFile);
	fputs("    levels:\n",outFile);
	
	switch(quality){
		case 1:
			temp1 = number;
			temp2 = numberlite;
			temp3 = money;			
			fputs("      普通:\n",outFile);
			fputs("        weight: 270\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f普通'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 2:
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 3:
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 4:
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 5:
			temp1 = number*2;
			temp2 = numberlite*2;
			temp3 = money*2;
			fputs("      传说:\n",outFile);
			fputs("        weight: 1\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6传说'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;	
		case 12:
			temp1 = number;
			temp2 = numberlite;
			temp3 = money;			
			fputs("      普通:\n",outFile);
			fputs("        weight: 270\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f普通'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 123:
			temp1 = number;
			temp2 = numberlite;
			temp3 = money;			
			fputs("      普通:\n",outFile);
			fputs("        weight: 270\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f普通'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2); 
			break;	
		case 1234:
			temp1 = number;
			temp2 = numberlite;
			temp3 = money;			
			fputs("      普通:\n",outFile);
			fputs("        weight: 270\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f普通'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2); 
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;	
		case 12345:
			temp1 = number;
			temp2 = numberlite;
			temp3 = money;			
			fputs("      普通:\n",outFile);
			fputs("        weight: 270\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&f普通'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2); 
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*2;
			temp2 = numberlite*2;
			temp3 = money*2;
			fputs("      传说:\n",outFile);
			fputs("        weight: 1\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6传说'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 23:
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 234:
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 2345:
			temp1 = number*1.2;
			temp2 = numberlite*1.2;
			temp3 = money*1.2;
			fputs("      优秀:\n",outFile);
			fputs("        weight: 90\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&a优秀'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*2;
			temp2 = numberlite*2;
			temp3 = money*2;
			fputs("      传说:\n",outFile);
			fputs("        weight: 1\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6传说'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 34:
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 345:
			temp1 = number*1.4;
			temp2 = numberlite*1.4;
			temp3 = money*1.4;
			fputs("      精良:\n",outFile);
			fputs("        weight: 30\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&3精良'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*2;
			temp2 = numberlite*2;
			temp3 = money*2;
			fputs("      传说:\n",outFile);
			fputs("        weight: 1\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6传说'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		case 45:
			temp1 = number*1.6;
			temp2 = numberlite*1.6;
			temp3 = money*1.6;
			fputs("      史诗:\n",outFile);
			fputs("        weight: 10\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '不可开孔'\n",outFile);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&d史诗'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			temp1 = number*2;
			temp2 = numberlite*2;
			temp3 = money*2;
			fputs("      传说:\n",outFile);
			fputs("        weight: 1\n",outFile);
			fputs("        颜色:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6'\n",outFile);
			fputs("        孔1:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔2:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔3:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔4:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔5:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        孔6:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%s'\n",mowen[type]);
			fputs("        鉴定品质:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fputs("          value: '&6传说'\n",outFile);
			fputs("        价值:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",temp3);
			fputs("        等级:\n",outFile);
			fputs("          type: fixed\n",outFile);
			fprintf(outFile,"          value: '%d'\n",level);
			fputs("        特殊值:\n",outFile);
			fputs("          type: strength\n",outFile);
			fprintf(outFile,"          base: %d\n",temp1);
			fprintf(outFile,"          add: %d\n",temp2);
			break;
		
	}
}







